@echo off
set CMAKE_GENERATOR=Ninja
set CMAKE_BUILD_TYPE=Debug
cmake -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -DCMAKE_GENERATOR=%CMAKE_GENERATOR% -DCMAKE_EXPORT_COMPILE_COMMANDS=1 . -B Build
ninja -C Build
Binaries\%1
